# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78b224980ca9f30f9f3b3de61c12192d1777e0b3276bef90b78f77acd1eeafc5d94fc27d54fa942735eb0d0ca1ddd9f9efd3fff97f15711a46a344dfa1d55cb

test:
  secret_key_base: 1187ad8eade7bb35ba6833b3007d4ee5484222f03ed6c1e534a716ebc54e47af43c97a97ff06a190161b427c6263d4e226a55f171786a12e34b1db197462a3bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
